# Generated by Django 2.2.28 on 2023-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='sdsds',
        ),
        migrations.AddField(
            model_name='hello',
            name='sdsdsdsdssd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
