# Generated by Django 2.2.28 on 2023-09-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customer_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloo',
            name='python',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
